title: Affordable Church Websites
email: "pastorryanhaydenl@gmail.com"
description: > # this means to ignore newlines until "baseurl:"
  Sitesfor.church makes affordable church websites built for the needs of the 90% of churches with less than 200 members.  
  You won't find a professional solution that is more affordable or easier to use.  We also are deliberate about giving jobs
  to Bible college students and other aspiring pastors.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://sitesfor.church/" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown
 
# Exclude
exclude:
  - package.json
  - node_modules
  - gulpfile.js 
  - bower_components
keep_files:
  - assets/css

# Airtable API Stuff
airtable:
  apikey: "keyRTLlrVS02vC3Vx"
  blog: "appSTMfI6fck1RzVM"

page_gen:
  - data: 'blog'
    template: 'post2'
    name: 'title'
    dir: 'blog'

collections:
  docs:
    output: true
    permalink: /docs/:path/
  srdocs:
    output: true


ftp_host: 'biblebaptistmattoon.org'
ftp_dir: 'sitesfor.church/'
ftp_passive: false
ftp_username: 'ryahay11'
ftp_password: '@88Volvocj'